services:
  backend:
    image: aleks4k/questionmark:latest
    ports:
      - "5222:5222"
    environment:
      - ASPNETCORE_URLS=http://+:5222
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
volumes:
  mysql_data: