// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using questionmark.Domain.Data;

#nullable disable

namespace questionmark.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407100307_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("questionmark.Domain.Entities.Comment", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("comment_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("ID"));

                    b.Property<DateTime>("date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("date_of_comment")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<uint>("post_id")
                        .HasColumnType("int unsigned")
                        .HasColumnName("post_id");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("varchar(512)")
                        .HasColumnName("text");

                    b.Property<uint>("user_id")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("ID");

                    b.HasIndex("post_id");

                    b.HasIndex("user_id");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("questionmark.Domain.Entities.Post", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("post_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("ID"));

                    b.Property<DateTime>("date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("date_of_post")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("varchar(512)")
                        .HasColumnName("text");

                    b.Property<uint>("user_id")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("ID");

                    b.HasIndex("user_id");

                    b.ToTable("post", (string)null);
                });

            modelBuilder.Entity("questionmark.Domain.Entities.Reaction", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("reaction_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("ID"));

                    b.Property<DateTime>("date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("date_of_reaction")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<uint>("post_id")
                        .HasColumnType("int unsigned")
                        .HasColumnName("post_id");

                    b.Property<ulong>("reaction")
                        .HasColumnType("bit(1)")
                        .HasColumnName("reaction");

                    b.Property<uint>("user_id")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("ID");

                    b.HasIndex("user_id");

                    b.HasIndex("post_id", "user_id")
                        .IsUnique()
                        .HasDatabaseName("uq_post_id_user_id");

                    b.ToTable("reaction", (string)null);
                });

            modelBuilder.Entity("questionmark.Domain.Entities.Session", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("session_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("ID"));

                    b.Property<DateTime>("end")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("session_end")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte[]>("hash")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasColumnName("session_hash");

                    b.Property<byte[]>("nonce")
                        .IsRequired()
                        .HasColumnType("binary(12)")
                        .HasColumnName("session_nonce");

                    b.Property<byte[]>("tag")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("session_tag");

                    b.HasKey("ID");

                    b.HasIndex("hash")
                        .IsUnique();

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("questionmark.Domain.Entities.User", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("ID"));

                    b.Property<byte[]>("auth")
                        .IsRequired()
                        .HasColumnType("binary(64)")
                        .HasColumnName("auth");

                    b.HasKey("ID");

                    b.HasIndex("auth")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("questionmark.Domain.Entities.Comment", b =>
                {
                    b.HasOne("questionmark.Domain.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("post_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("questionmark.Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("questionmark.Domain.Entities.Post", b =>
                {
                    b.HasOne("questionmark.Domain.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("questionmark.Domain.Entities.Reaction", b =>
                {
                    b.HasOne("questionmark.Domain.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("post_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("questionmark.Domain.Entities.User", "User")
                        .WithMany("Reactions")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("questionmark.Domain.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("questionmark.Domain.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");

                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
